### ISSUE TITLE
Add SourcePawn Icon

### ISSUE THREAD

**Issue by traditionalism** [iCrawl/discord-vscode#1007]
Add SourceMod/SourcePawn logo as pull #995 the other day add's SourcePawn but it has no large image.

PR for SP files: #995 
SHA1: 2f26a93ed11beaa930460105ea8c3583ac854d05

# Example: 
![DiscordCanary_6VwSptyiIA](https://user-images.githubusercontent.com/57818674/114952846-c8cbbb80-9e1c-11eb-9dea-2f5526bf8e6e.png)

# Large Image:
![sp](https://user-images.githubusercontent.com/57818674/114952871-d08b6000-9e1c-11eb-956a-b978c6d42110.png)

**Comment by jacany** [comment]
🚀

**Comment by jacany** [comment]
this would be nice, currently it's just blank with no images at all :/

**Comment by ivenuss** [comment]
+1

**Comment by strafe** [comment]
I didn't include this in my PR because it's not actually associated with the language itself, rather with the SourceMod project (a Metamod plugin). Including this or the AlliedModders logo just didn't make sense to me. Additionally, SourcePawn (the language in question) actually has its own logo which should take precedence over this if one is going to be used:
![](https://alliedmods.net/media/logos/SourcePawnWCorner.png)

Personally I prefer the Pawn logo that is currently in the extension, so I requested that be used for both but I don't think iCrawl has had time to get around to it yet.
