### ISSUE TITLE
Couldn't connect to Discord via RPC: Error: write EPIPE

### ISSUE THREAD

**Issue by chico-edd** [iCrawl/discord-vscode#236]
Hi, i've been trying to run the extension for a really long time, i run Visual Studio Code and Stable Discord.
i have tried reinstalling the extension, restarting VSC, also Discord, also i've tried disabling and enabling the extension, i don't know what to do at this point.
![image](https://user-images.githubusercontent.com/45445665/56262737-3f524900-609d-11e9-91a0-4cae424d69cd.png)

**Comment by iCrawl** [comment]
"write EPIPE" is probably the most generic windows error you can get.

Try restarting your PC and try again. If it still doesn't work no idea. There's no way to pinpoint the problem.

**Comment by chico-edd** [comment]
Yeah, i just noticed something was wrong with the machine, and i did a hard reset, thanks for the response!

**Comment by diogopaulos** [comment]
I don't remember if mine said `Error: write EPIPE`, but my discord was running on administrator. Since it was on administrator, vscode could not connect to my discord. Try checking your discord compatibility settings by right clicking Discord icon, then `Properties > Compatibility > Run this program on administrator`.
