### ISSUE TITLE
[Request] Chose from VSCode and VSCodium (FLOSS version)

### ISSUE THREAD

**Issue by auyer** [iCrawl/discord-vscode#260]
As some might now, the official VSCode binaries are not 100% open source, and contains trackers.
Thats why the [VSCodium](https://github.com/VSCodium/vscodium) distribuiton exists: binary releases of VS Code without MS branding/telemetry/licensing.

As a VSCodium user, I would like to be able to chose VSCosium instead of "Visual Stuio Code" text and logo. Or if possible, this could be detected automatically.

VSCodium Logo: https://github.com/VSCodium/vscodium/blob/master/src/resources/linux/code.png

**Comment by vladfrangu** [comment]
Out code bases off `{appname}`, which returns whatever version of vscode you use. Since VSCodium is still, at it's core, VSCode, that returns instead.

For the small image text, you can set `discord.smallImage` in your VSC Settings. As for the app name... You cannot change that, as it's tied to the client ID for the rich presence. You *can* create your own Discord app for it, but that is also pretty tedious.
