### ISSUE TITLE
command 'discord.reconnect' not found

### ISSUE THREAD

**Issue by Iskawo** [iCrawl/discord-vscode#374]
I have installed this plugin, but it's not working, and when i click "Reconnect to Discord", it says **command 'discord.reconnect' not found**
Here is a gif: https://i.iskawo.xyz/lDPWiIi839.gif

**Comment by LolWastedJS** [comment]
@Iskawo I also had this issue :/

**Comment by iCrawl** [comment]
This comes up every once in a while, and I have no idea how to reproduce it.

Try updating/reinstalling (VSCode too), or use Insiders. For some this fixed it, the code itself is fine since I do register the commands just fine, and it doesn't break for everyone all of a sudden either.

**Comment by Schobbish** [comment]
I've had this issue for a while and eventually switched to a different extension. However, said extension wasn't good so I wanted to give this another try. It turns out I had an invalid configuration: for `discord.workspaceExcludePatterns` I had `["*blah"]`, which throws `SyntaxError: Invalid regular expression: /*blah/: Nothing to repeat` in the Extension Host logs. Removing that pattern (and reloading) fixed it for me. (I also see what I did wrong: it's supposed to be a 'proper' regex, not a file globbing thing.)

So a fix for future people who have this problem could be to check for invalid config or remove all config for the extension.
