### ISSUE TITLE
why not vscode-discord?

### ISSUE THREAD

**Issue by fourjr** [iCrawl/discord-vscode#4]

**Comment by iCrawl** [comment]
* Maintainable codebase.
* Features over 50+ languages, and if I missed one you can always hit me up.
* Follows VSCode extension standards.

Not to mention that I do not send constant activity updates if you are editing the same file. I only update the status when you are editing another file instead of constantly sending an update.

**Comment by fourjr** [comment]
Thank you for the response, is there a way I can change the messages/client ID?

**Comment by iCrawl** [comment]
Yes I provided it. You can simply change the client ID in the settings.json via discord.clientID. Make sure it is a string.

**Comment by fourjr** [comment]
I'm reading the code from https://github.com/iCrawl/discord-vscode/blob/master/src/extension.ts#L147 and was wondering what is the default key name if the file ext asset is not found (for large image)
