### ISSUE TITLE
{gitreponame} still doesn't work...

### ISSUE THREAD

**Issue by pozm** [iCrawl/discord-vscode#690]
in issue #616 you said that it should be fixed in most recent version, but the most recent is 4.0.0 and it still doesn't work.
<img src = https://i.imgur.com/zSdClzg.png>
i have it in settings, yet in discord it will either display {gitreponame} or Uknown (intended functionality) depending if the folder uses github.

my settings:
<img src = https://i.imgur.com/LK3d2g1.png>
discord view:
<img src= https://i.imgur.com/Xl0KRbi.png>

I have reinstalled multiple times with no avail.

**Comment by LoaderB0T** [comment]
Hi there, I have the exact same issue.
![image](https://user-images.githubusercontent.com/37637338/97083774-b6fa2000-1612-11eb-9697-18c679d28388.png)

**Comment by IchiiDev** [comment]
I don't know if it's the same issue but it seems to be the same cause with `{gitbranch}` I tried to add the tag after the workspace one but whenever I try to switch on an editable file, I'm still displayed as idling
Before:
![](https://i.discord.fr/e1d.png)
![](https://i.discord.fr/ggO.png)

After:
![](https://i.discord.fr/Bb6.png)
![](https://i.discord.fr/YnC.png)

It seem this issue is touching the git info tags, maybe they changed since an update of VS Code

**Comment by xFGhoul** [comment]
sorry this may be late @pozm , But what is that discord background and how do I get it?

**Comment by iCrawl** [comment]
Should work fine in v5 now, if it doesn't work that simply means it cannot find your git installation or you use WSL without having git installed in windows.
