### ISSUE TITLE
Says "Connected to Discord" yet nothing shows up as my status

### ISSUE THREAD

**Issue by Tresquel** [iCrawl/discord-vscode#943]
Yup
It says "Connected to Discord" and my status on discord isn't changing
```
OS: Windows 10
Build: 19042.844 (20H2)
VSCode version: 1.53.2
Plugin version: 5.4.0
```
if you need any more info lmk

**Comment by ImBoing** [comment]
This happened to me too I cant get it to show up on my status

**Comment by LFGaming** [comment]
for me too, for me its since i updated the plugin i think, but going back to older versions doesn't help me. because it broken there too.

**Comment by iCrawl** [comment]
I'll copy this from my answer in Discord:

> Yeah, it's not
This is just an ongoing issue with VSCode not being able to connect to your discord RPC instance
It may take several restarts of either VSCode or discord
Theres no surefire way, and the percentage of people where it's bugged in that state is extremely low
It's not an issue with the extension, since all RPC extensions that are out there (written in JS) use the exact same method and code

I know it might not be the answer some of you want to hear, but there is really nothing wrong with the extension as far as I know. All the other extensions written in JS are the completely same (whether that be a fork of this, or another VSCode Discord one, or even a completely different one like PreMiD) at the end of the day.

**Comment by LFGaming** [comment]
If you go to your settings and turn on the "Display current running games as a status message" in the games activity section on then it worked again for me. maybe you can try that too @Tresquel and @ImBoing

**Comment by Tresquel** [comment]
> If you go to your settings and turn on the "Display current running games as a status message" in the games activity section on then it worked again for me. maybe you can try that too @Tresquel and @ImBoing 
> ![Discord_2021-03-10_14-28-32](https://user-images.githubusercontent.com/38732192/110637192-6c3a0880-81ad-11eb-90a3-fc4ff34f6680.png)
> 

yup that fixed it thx
